"""sync schema with models

Revision ID: 1d4ae3b7d398
Revises: b0e318cfb76a
Create Date: 2026-08-23 18:56:19.995695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4ae3b7d398'
down_revision = 'b0e318cfb76a'
branch_labels = None
depends_on = None


def _has(table, column=None):
    """Databases created by the old db.create_all() already contain some of
    this, so every step is applied only when it is actually missing."""
    from alembic import op as _op
    insp = sa.inspect(_op.get_bind())
    if not insp.has_table(table):
        return False
    if column is None:
        return True
    return column in {c['name'] for c in insp.get_columns(table)}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has('booking_intents'):
      op.create_table('booking_intents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        if not _has('clubs', 'latitude'): batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        if not _has('clubs', 'longitude'): batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        if not _has('clubs', 'amenities'): batch_op.add_column(sa.Column('amenities', sa.JSON(), nullable=True))
        if not _has('clubs', 'tags'): batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))

    with op.batch_alter_table('courts', schema=None) as batch_op:
        if not _has('courts', 'amenities'): batch_op.add_column(sa.Column('amenities', sa.JSON(), nullable=True))
        if not _has('courts', 'tags'): batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))

    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        # price_monthly -> price is a rename, not a drop + add: doing it as
        # add/drop would discard existing plan pricing.
        batch_op.alter_column('price_monthly', new_column_name='price',
                              existing_type=sa.Float(), nullable=False)
        if not _has('membership_plans', 'duration_months'): batch_op.add_column(sa.Column('duration_months', sa.Integer(),
                                      nullable=False, server_default='1'))
        if not _has('membership_plans', 'discount_percentage'): batch_op.add_column(sa.Column('discount_percentage', sa.Float(), nullable=True))
        if not _has('membership_plans', 'created_at'): batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.alter_column('club_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.alter_column('club_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.alter_column('club_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.alter_column('price', new_column_name='price_monthly',
                              existing_type=sa.Float(), nullable=False)
        batch_op.alter_column('club_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('duration_months')

    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('amenities')

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('amenities')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    op.drop_table('booking_intents')
    # ### end Alembic commands ###
