"""add user profile fields and preferences

Revision ID: b0e318cfb76a
Revises: f05db257887e
Create Date: 2026-08-21 01:45:24.724816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e318cfb76a'
down_revision = 'f05db257887e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('notify_email', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('notify_sms', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('notify_push', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('profile_public', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_public')
        batch_op.drop_column('notify_push')
        batch_op.drop_column('notify_sms')
        batch_op.drop_column('notify_email')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('address')
        batch_op.drop_column('gender')
        batch_op.drop_column('dob')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
